/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package load.and.apply

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient
import software.amazon.awssdk.services.dynamodb.DynamoDbClient


@SpringBootApplication
@Configuration
class App {
    val greeting: String
        get() {
            return "Hello world."
        }

    @Bean
    fun dynamoClient():DynamoDbClient{
        return DynamoDbClient.create()
    }

    @Bean
    fun enhancedDynamoClient(standardClient: DynamoDbClient): DynamoDbEnhancedClient {
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(standardClient)
                .build()
    }

}

object AppStarter {

    @JvmStatic
    fun main(args: Array<String>) {
        SpringApplication.run(App::class.java, *args)
    }

}
